version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    env_file:
      - .env
    ports:
      - "5433:5432" # Map host port 5433 to container port 5432
    networks:
      - app_network
    restart: always # Restart policy for resilience

  app:
    build:
      context: .
    container_name: mcp_postgres_server
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app_network
    restart: always # Restart policy for resilience

networks:
  app_network:
    driver: bridge
